### ISSUE TITLE
Query log option flutterhole v5.1.2 

### ISSUE THREAD

**Issue by bumfuzzle-git** [sterrenburg/flutterhole#101] opened 2020-06-14 09:06 UTC
In version v5.1.2 build #629

Please readd the option like in the older versions to be able to whitelist & blacklist the urls in the query log. It was very convenient to open the app, refresh and check the logs and make the action instantly. 

#best app for pihole on android :)

Thanks

**Comment by sterrenburg** [comment] 2020-06-16 14:01
Hello @bumfuzzle-git 👋 - Thanks for opening an issue!

This sounds like a duplicate of #76. The Pi-hole API currently has a bug that prevents the app from accessing the black-/whitelist. Please check out #76 for progress, or if you meant something else, feel free to re-open this issue. Hope this helps.

**Closed by sterrenburg** 2020-06-16 14:01 UTC
